### ISSUE TITLE
Color in Logfile

### ISSUE THREAD

**Issue by CCCCarsten** [RHazDev/NetworkMessages#2]
Only a minor error I want to report: The use of your plugin is the reason because in the Bungeecord logfile player logins or player logoffs are no longer displayed in color. This would be important to me but for the sake of clarity.

**Comment by hazae41** [comment]
So, you want to add network messages to the BungeeCord log, right?

**Comment by CCCCarsten** [comment]
No :) I only want to have back the color :). 

11:51:50 [WARNUNG] Event PreLoginEvent(cancelled=false, cancelReasonComponents=null, connection=[Player_Hd_K] <-> InitialHandler) took 308.532.236ns to process!
11:51:51 [INFORMATION] [Player_Hd_K] <-> ServerConnector [skyblock-ultimate] has connected

11:34:34 [INFORMATION] [Player_Hd_K] -> UpstreamBridge has disconnected

The above mentioned entrys (logfile of bungeecord) are colored, if I am *not* using your plugin.

**Comment by hazae41** [comment]
That's weird
What happens when using Kotlin4MC without NetworkMsgs?
And without both?

**Comment by hazae41** [comment]
Has the problem been fixed with the last update of Kotlin4MC?

**Comment by CCCCarsten** [comment]
I apologize very much! It is obviously not your plugin, which prevents the colors in the logfile. :(
